spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: mymicroservicecloud-config-atguigu-dev01
---
spring:
  profiles: test
  application:
    name: mymicroservicecloud-config-atguigu-test01
