spring:
  profiles:
    active:
    - dev
spring:
  profiles: dev
  application:
    name: mymicroservicecloud-config-atguigu-dev1
spring:
  profiles: test
  application:
    name: mymicroservicecloud-config-atguigu-test1
