spring:
  profiles: 
    active: 
    - dev
---
spring:
  profiles: dev #开发环境
  application: 
    name: mymicroservicecloud-config-atguigu-dev
---
spring:
  profiles: test #测试环境
  application:
    name: mymicroservicecloud-config-atguigu-test
#保存为UTF-8