spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: mymicroservicecloud-config-clinet
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: mymicroservicecloud-config-clinet1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/